name: CD to staging

on:
  check_run:
    types: [completed]

jobs:
  deployStaging:
    if: github.ref_name != 'staging'
    strategy:
      matrix:
        target: [dev, stage]
    uses: ./.github/workflows/FE-build.yml
    with:
      target: ${{ matrix.target }}