name: CD to staging

on:
  workflow_run:
    workflows: [GitHub Actions Demo]
    types:
      - completed

jobs:
  deployStaging:
    if: github.ref_name != 'staging'
    strategy:
      matrix:
        target: [dev, stage]
    uses: ./.github/workflows/FE-build.yml
    with:
      target: ${{ matrix.target }}