name: CD to staging

on:
  workflow_run:
    workflows: [GitHub Actions Demo]
    types:
      - completed

jobs:
  deployStaging:
    strategy:
      matrix:
        target: [dev, stage]
    uses: ./.github/workflows/FE-build.yml
    with:
      target: ${{ matrix.target }}

  deployStaging2:
    strategy:
      matrix:
        target: [dev, stage]
    uses: ./.github/workflows/FE-build.yml
    with:
      target: ${{ matrix.target }}

  deployStaging3:
    strategy:
      matrix:
        target: [dev, stage]
    uses: ./.github/workflows/FE-build.yml
    with:
      target: ${{ matrix.target }}
