name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployStaging:
    strategy:
      matrix:
        target: [dev, stage]
    uses: ./.github/workflows/FE-build.yml
    with:
      target: ${{ matrix.target }}

  deployStaging2:
    strategy:
      matrix:
        target: [dev, stage]
    uses: ./.github/workflows/FE-build.yml
    with:
      target: ${{ matrix.target }}

  deployStaging3:
    strategy:
      matrix:
        target: [dev, stage]
    uses: ./.github/workflows/FE-build.yml
    with:
      target: ${{ matrix.target }}
